1.0.3 - custom_sections for organzing module sections
- support 'default' as scalar or hash

diff --git a/bin/orepan2-s3 b/bin/orepan2-s3
--- a/bin/orepan2-s3
+++ b/bin/orepan2-s3
@@ -38,7 +38,7 @@ Notes
 
 2. default configuration file is .orepan2-s3.json and should be in your home directory
 
-3. you must provide either -t TAG-VALUE or -d DISTRIBUTIO-id
+3. you must provide either -t TAG-VALUE or -d DISTRIBUTION-ID
 
 EOF
 
@@ -48,9 +48,18 @@ EOF
 ########################################################################
 find_config_name() {
 ########################################################################
+    set -x
     local config_file="$1"
     local config_profile="${2:-default}"
 
+    if ! jq -e '(.default | type) == "object"' $config_file >/dev/null; then
+        config_profile=$(jq -r ".$2" $config_file)
+        if ! jq -e '(.'$config_profile' | type ) == "object"' $config_file >/dev/null; then
+            echo >&2 "ERROR: can't determine config profile"
+            exit 1;
+        fi
+    fi
+    
     local path_prefix=".${config_profile}.index"
 
     local index=$(cat $config_file | jq -r "$path_prefix? //\"\"")
@@ -71,7 +80,7 @@ find_config() {
 
     local path="$config_profile.index? //\"\""
 
-    cat $config_file | jq -r  "$path"
+    cat $config_file | jq -r "$path"
 }
 
 ########################################################################
@@ -270,7 +279,6 @@ add() {
 ########################################################################
 set_defaults() {
 ########################################################################
-
     local profile_name=$(find_config_name "$CONFIG_FILE" "$PROFILE_NAME")
     local config=$(cat "$CONFIG_FILE" | jq -r ".$profile_name")
 
@@ -282,7 +290,7 @@ set_defaults() {
 
     AWS_ACCOUNT=$(echo "$CONFIG" | jq -r '.AWS.account // ""')
     test -z "$AWS_ACCOUNT" && AWS_ACCOUNT=$($AWS sts get-caller-identity --query 'Account' --output text --profile "$AWS_PROFILE")
-
+    CONFIG=$config
 }
 
 ########################################################################
@@ -425,7 +433,7 @@ INVALIDATION_PATHS+=("/$PATH_PREFIX/orepan2-cache.json")
 INVALIDATION_PATHS+=("/index.html")
 INVALIDATION_PATHS+=("/docs/*")
 
-for p in $(cat $CONFIG_FILE | jq -r '.default.CloudFront.InvalidationPaths? //[]|.[]|.'); do 
+for p in $(echo $CONFIG | jq -r '.CloudFront.InvalidationPaths? //[]|.[]|.'); do 
     test -n "$VERBOSE" && echo "adding custom invalidation path: $p" >&2
     INVALIDATION_PATHS+=("$p")
 done
